### ISSUE TITLE
Miscord cannot start

### ISSUE THREAD

**Issue by tanpro260196** [miscord/miscord#280]
**Describe the bug**
Does not start from command promt on Windows Server 2012

**Expected behavior**
This error message show up in Command Promt:
```
C:\Users\Administrator\OneDrive\TEARaria_Main\MessengerBot>miscord.exe
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Cannot find module 'entities/lib/decode_codepoint.js'
1) If you want to compile the package/file into executable, please pay attention
 to compilation warnings and specify a literal in 'require' call. 2) If you don'
t want to compile the package/file into executable and want to 'require' it from
 filesystem (likely plugin), specify an absolute path in 'require' call using pr
ocess.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\miscord\node_modules\htmlparser2\lib\Toke
nizer.js:3:23)
    at Module._compile (module.js:650:30)
    at Module._compile (pkg/prelude/bootstrap.js:1259:32)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
```

**Specifications:**
 - OS: Windows Server 2012 R2
 - Version (`3.8.2`)
 - Node.js version (`8.11.3`)

**Comment by Bjornskjald** [comment]
Known issue with 3.8.2 binaries, will be fixed in 3.8.3. Closing
