### ISSUE TITLE
Question - Is it possible to catch the API error that can occur after the message is sent?

### ISSUE THREAD

**Issue by ajstewart** [miscord/miscord#285]
I'm specifically asking about cases such as this (the one thing I'm looking for is feedback to users when things go wrong and their message doesn't get through):

```
verb discordListener: username Bob
sill discordListener: message { body: '*Bob*\nI\'m keen for a couple of Ho-Oh raids if we can get numbers up today. Not at campus yet but will be in half an hour.',
sill discordListener: message   attachment: [] }
verb discordListener: threads [ '1640815462627203' ]
verb discordListener Sent message on Messenger
WARN parseAndCheckLogin Got status code 500 - 1. attempt to retry in 1996 milliseconds...
ERR! sendMessage Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! sendMessage     at /usr/lib/node_modules/miscord/node_modules/facebook-chat-api/utils.js:1042:15
```
... other standard 404 error ... ending with
```
ERR! sendMessage     at Promise._settlePromiseAt (/usr/lib/node_modules/miscord/node_modules/bluebird/js/main/promise.js:584:18)
ERR! sendMessage     at Async._drainQueue (/usr/lib/node_modules/miscord/node_modules/bluebird/js/main/async.js:128:12)
ERR! sendMessage     at Async._drainQueues (/usr/lib/node_modules/miscord/node_modules/bluebird/js/main/async.js:133:10)
ERR! sendMessage     at Immediate.Async.drainQueues (/usr/lib/node_modules/miscord/node_modules/bluebird/js/main/async.js:15:14)
ERR! sendMessage     at runCallback (timers.js:810:20)
ERR! sendMessage     at tryOnImmediate (timers.js:768:5)
ERR! sendMessage     at processImmediate [as _immediateCallback] (timers.js:745:5)
verb messengerListener Got Messenger event, type: message
info messengerListener Got a Messenger message
```

(I can go back and get the full log).

**Comment by Bjornskjald** [comment]
If it doesn't crash, then it's not sent to Miscord and displayed only by facebook-chat-api, so... probably not.

**Comment by ajstewart** [comment]
Ok yes I was thinking that might be the case - I guess it would need some changes to the API to get something like that?

**Comment by ajstewart** [comment]
p.s. just linking this here for reference: https://github.com/Schmavery/facebook-chat-api/issues/655

as this is the error.

**Comment by Bjornskjald** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/61ddf3ce02767ac5c04f93232567cc7e67fb1afe/src/sendMessage.js#L171

apparently it's being sent in the callback...

**Comment by ajstewart** [comment]
I always thought the callback should catch it but it never seems to trigger, hence why I was asking as I could never seem to understand why it wasn't. I may monitor it some more to try and work it out.

**Comment by Bjornskjald** [comment]
Closing due to inactivity.

**Comment by ajstewart** [comment]
Hi, so I think I am seeing the error messages ok, at least when I see the error message in the channel I can match it to the message that caused an error. It may have been edits that made to the code that was causing the non-pass through before.

This leads me back to ask if there is any way there could be an optional feature such that if an error is raised in the send message in Discord listener, it would notify the Discord user who sent the message? As currently they have no idea that the message didn't make it.
