### ISSUE TITLE
Truncate message when over 2000 characters to avoid crash

### ISSUE THREAD

**Issue by BallsOfSpheal** [miscord/miscord#288]
Recently a large announcement was sent messenger > discord resulting in the following error.

Invalid Form Body
content: Must be 2000 or fewer in length.
DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at item.request.gen.end (/usr/local/lib/node_modules/miscord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
    at then (/usr/local/lib/node_modules/miscord/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Causing the bridge to go down.

**Comment by PixelHir** [comment]
It's kinda related to the #274. (proper error handling?)

**Comment by Bjornskjald** [comment]
Yup, could close as a duplicate but I think it's better to keep them as separate issues. (mostly because this one is much simpler to fix 😄)
