### ISSUE TITLE
it spits me an error everytime i try to run it

### ISSUE THREAD

**Issue by gpj252** [miscord/miscord#316]
```
Verifying archive integrity...  100%   All good.
Uncompressing Miscord/snap/miscord/56/bin/miscord: 80: /snap/miscord/56/bin/miscord: df: Permission denied
  100%  chown: changing ownership of './miscord-3.7.4-linux-x64': Operation not permitted
chown: changing ownership of '.': Operation not permitted
/snap/miscord/56/bin/miscord: 542: /snap/miscord/56/bin/miscord: chgrp: Permission denied

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at NativeModule.compile (bootstrap_node.js:632:7)
    at NativeModule.require (bootstrap_node.js:577:18)
    at net.js:45:13
    at NativeModule.compile (bootstrap_node.js:632:7)
    at NativeModule.require (bootstrap_node.js:577:18)
    at tty.js:25:13
    at NativeModule.compile (bootstrap_node.js:632:7)
    at NativeModule.require (bootstrap_node.js:577:18)
```

**Comment by Bjornskjald** [comment]
Oh, don't run the snap version, it's outdated. Use NPM or binaries instead

**Comment by gpj252** [comment]
oh, thanks for the fast response, will do that ^^

**Comment by gpj252** [comment]
worked like a charm, thanks for the tip
