### ISSUE TITLE
Running multiple config on same server

### ISSUE THREAD

**Issue by lhovo** [miscord/miscord#322]
**Describe the bug**
When trying to run two instances of miscord with two different config (including different credentials and discord bot) like:
screen -d -m miscord --config ~/config_wrg.json
screen -d -m miscord --config ~/config.json

The first instance exits with a error,
when re running the first again the second exits with the same error.
I have tried this a few times now and I'm just toggling with only one ever running.

```
/usr/local/lib/node_modules/miscord/node_modules/libfb/dist/mqtt/MqttConnection.js:42
                throw new Error('Connection closed.');
                ^

Error: Connection closed.
    at TLSSocket.socket.on._ (/usr/local/lib/node_modules/miscord/node_modules/libfb/dist/mqtt/MqttConnection.js:42:23)
    at TLSSocket.emit (events.js:187:15)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:386:7)
```

**To Reproduce**
1. pkg install npm node
2. npm install -g miscord
3. screen -d -m miscord --config ~/config_wrg.json
4. screen -d -m miscord --config ~/config.json

**Expected behavior**
I would have expected the two instances would live happily running on the same machine.

**Screenshots**
<img width="835" alt="screen shot 2018-10-08 at 11 11 54 pm" src="https://user-images.githubusercontent.com/184518/46611059-01092980-cb50-11e8-83cc-b9d61082a64d.png">

**Specifications:**
 - OS: Freebsd 11.2
 - Version (`miscord -v`) 4.0.2
 - Node.js version (`node -v`) v10.11.0

**Additional context**

**Comment by Bjornskjald** [comment]
First of all, you should keep your config in separate directories. Miscord creates another files alongside config in its directory and it may be interfering between two instances.
