### ISSUE TITLE
Messenger plans crash version 4.1.1 (and other plan issues)

### ISSUE THREAD

**Issue by ajstewart** [miscord/miscord#330]
**Describe the bug**

When a plan is created in Messenger, Miscord currently crashes with the following error message:

```
[2018-10-13 00:42:14] … debug messenger › getChannelName › raw channel name
[2018-10-13 00:42:14]   Miscord testing
[2018-10-13 00:42:14] … debug messenger › getChannelName › clean channel name
[2018-10-13 00:42:14]   miscord-testing
[2018-10-13 00:42:14] … trace messenger › filter › whitelist
[2018-10-13 00:42:14]   [ '1640815462627203', '1646978945423790' ]
[2018-10-13 00:42:14] … debug messenger › getSender › Getting sender from API
[2018-10-13 00:42:15] ✖ error errorHandler › TypeError: Cannot read property 'name' of undefined
[2018-10-13 00:42:15]   at going.map.el (/home/ec2-user/.npm-global/lib/node_modules/miscord/lib/messenger/handlePlan.js:17:121)
  at Array.map (<anonymous>)
  at module.exports (/home/ec2-user/.npm-global/lib/node_modules/miscord/lib/messenger/handlePlan.js:17:108)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:189:7)
```

As said in the error message the error is coming from:

https://github.com/miscord/miscord/blob/284eef13711f4fc30e21d06b67bcce34830ad811/lib/messenger/handlePlan.js#L17

Which in turn is coming from `getSender.js` as it returns the undefined.

I noticed that for all plans `getSender.js` is reporting that it gets the sender from the API (which I believe shouldn't usually be the case as all the information is there in `messenger.senders`.

For normal text messages from Messenger the sender is indeed got from the cache. So further digging I noticed that the line above is sending the `senderID` as a string where as they are stored in the cache as a Number. This may also explain why the get from API wasn't working.

I can avoid the crash by forcing the `el.id` to be a Number above but then there seems to be other issues as passed to Discord is that below which is missing all the plan details:

![screen shot 2018-10-13 at 13 34 17](https://user-images.githubusercontent.com/3306161/46900368-bdfedb80-ceec-11e8-84a1-20d2affe598c.png)
 
Which I found odd as sending `going` to the log shows the correct name, so for some reason the event info isn't being passed. I didn't investigate this reason. Perhaps something to do with the undefined message that seems to be appearing.

EDIT: The undefined message appears when a plan is created.

**To Reproduce**

Create a plan in a messenger chat while running Miscord v4.1.1

**Expected behavior**

Messenger plans show as they did pre version 4.

**Comment by Bjornskjald** [comment]
Thanks for a detailed description, I'll try to fix it as soon as possible.

**Comment by ajstewart** [comment]
To add to this I’ve just seen that plans aren’t being passed to the group chat channel. Something was coming through on my testing channel as above, but the one with 200+ members doesn’t seem to show anything. Things always seem to go a bit strange in large group channels.
