### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [miscord/miscord#345]
Hello,

I'm new in the Miscrod world, so a probably didn't configure it correctly.
I use version 4.1.5.

Miscord shut down randomly, when someone writes a message on Messenger, and get this error : 

> Cannot read property 'name' of undefined
> TypeError: Cannot read property 'name' of undefined
>     at Object.module.exports [as discord] (C:\snapshot\miscord\lib\createMessage\fromMessenger.discord.js:10:117)
>     at module.exports.Promise.all.channels.map (C:\snapshot\miscord\lib\messenger\listener.js:36:48)
>     at Array.map (<anonymous>)
>     at ApiEmitter.module.exports (C:\snapshot\miscord\lib\messenger\listener.js:35:30)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Thanks for your help.

**Comment by gdcfxvnjvbncvb** [comment]
I didn't get this error with version 4.1.4 of Miscord.

**Comment by Bjornskjald** [comment]
(apparently it means the sender is undefined)

**Comment by Bjornskjald** [comment]
Also, it should be working in 4.1.6.

**Comment by gdcfxvnjvbncvb** [comment]
Didn't have this problems on 4.1.3.
I upgraded to 4.1.6, and didn't have this problem.
