### ISSUE TITLE
Error: Connection closed.

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [miscord/miscord#348]
**Describe the bug**
Miscord randomly closes letting the following report on the "error reports channel" : 
> Connection closed.
> Error: Connection closed.
>     at TLSSocket.connect.tslib_1.__awaiter.socket.on._ (C:\snapshot\miscord\node_modules\libfb\dist\mqtt\MqttConnection.js:42:23)
>     at TLSSocket.emit (events.js:187:15)
>     at _handle.close (net.js:595:12)
>     at TCP.done [as _onclose] (_tls_wrap.js:383:7)

**To Reproduce**
Let Miscord run for at least 24 hours. It happens at least once every 24 hours.

**Specifications:**
 - OS: Windows 10 1809 x64
 - Version Miscord 4.1.4
 - Node.js version ???

**Additional context**
For the moment, I downgraded to 4.1.3, to see if I get the same problems.

**Comment by aholekamp** [comment]
Miscord v4.1.6  
OS - Debian Linux (Raspberry Pi)
This exception was thrown 20 times today alone.  I had been running v4.1.0, and did not see these errors.  Willing to provide data to help debug as needed.

**Comment by ShinNinth** [comment]
I am also running into this issue with 4.1.6 on Debian Raspberry Pi.  I was going to downgrade but I have long forgotten the command to downgrade the NPM global package lol.  Currently I have been looking into a method of getting it to just auto restart on failure.

**Comment by gdcfxvnjvbncvb** [comment]
Follow up : I upgraded to 4.1.6 (Windows 10 1809 x64), and don't have this problem anymore.

**Comment by Foodzo** [comment]
I noticed it usually crashes when somebody sends a link on messenger. Some links are fine, but some cause the crash.

**Comment by Bjornskjald** [comment]
@Foodzo thanks, I'll look more into that.

**Comment by gpw81442** [comment]
Crashes when attempting login to Facebook.  I was just setting it up for the first time.  Performed a couple of message tests between Discord and FB.  Shut down and restarted only to crash.
OS is Win10

i info getConfig » Using config at C:\Users\ww\AppData\Roaming\Miscord\config.json
[2018-10-30 01:30:40] * start Launching Miscord v4.1.6
[2018-10-30 01:30:40] * start login » Logging in...
[2018-10-30 01:30:40] i info login » logLevel
[2018-10-30 01:30:40]   info
[2018-10-30 01:30:40] * start discord » login » Logging in to Discord...
[2018-10-30 01:30:41] √ success discord » login » Logged in to Discord
[2018-10-30 01:30:41] * start messenger » login » Logging in to Facebook...
[2018-10-30 01:30:41] × error errorHandler » Error: Connection closed.
[2018-10-30 01:30:41]   at TLSSocket.connect.tslib_1.__awaiter.socket.on._ (C:\snapshot\miscord\node_modules\libfb\dist\mqtt\MqttConnection.js:42:23)
  at TLSSocket.emit (events.js:187:15)
  at _handle.close (net.js:595:12)
  at TCP.done [as _onclose] (_tls_wrap.js:383:7)
[2018-10-30 01:30:41] 
[2018-10-30 01:30:41]

**Comment by gdcfxvnjvbncvb** [comment]
Got the problem on 4.1.0,  4.1.3,  4.1.4,  4.1.6
Windows 10 x64
