### ISSUE TITLE
"Cannot set property 'readonly' of undefined"

### ISSUE THREAD

**Issue by rnickson** [miscord/miscord#351]
**Describe the bug**
This often shows on my Discord info channel:
```
Cannot set property 'readonly' of undefined
TypeError: Cannot set property 'readonly' of undefined
    at channels.getConnection.filter.map.channel (/usr/local/lib/node_modules/miscord/lib/ConnectionsManager.js:72:85)
    at Array.map (<anonymous>)
    at ConnectionsManager.getChannels (/usr/local/lib/node_modules/miscord/lib/ConnectionsManager.js:72:8)
    at ApiEmitter.module.exports (/usr/local/lib/node_modules/miscord/lib/messenger/listener.js:31:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
idk

**Expected behavior**
Not throwing the error twice an hour.

**Specifications:**
 - OS: Ubuntu Server 18.04 (note that Miscord runs from Docker)
 - Version (`miscord -v`) 4.1.6
 - Node.js version (`node -v`) v10.20.0

**Additional context**
My config (from Discord command):
```
{
  "messenger": {
    "whitelist": [],
    "format": "{message}",
    "sourceFormat": {
      "discord": "(Discord)",
      "messenger": "(Messenger: {name})"
    },
    "ignoreEmbeds": false,
    "attachmentTooLargeError": false,
    "username": "***",
    "password": "***"
  },
  "discord": {
    "renameChannels": true,
    "showEvents": true,
    "showFullNames": false,
    "createChannels": true,
    "massMentions": true,
    "userMentions": true,
    "token": "***"
  },
  "timestamps": {
    "console": false,
    "logs": true
  },
  "channels": {
    "command": "507646083271491614",
    "error": "507646083271491614"
  },
  "checkUpdates": true,
  "logLevel": "info",
  "path": "/config"
}
```

**Comment by Bjornskjald** [comment]
Could you give me info about your connections? That looks like an error from connection manager

**Comment by Bjornskjald** [comment]
Found it. Your Discord channel ID is incorrect.

**Comment by rnickson** [comment]
Which one?

**Comment by Bjornskjald** [comment]
I have no idea, you have to go through your connections.yml and find out
