### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by unionofficial2009** [miscord/miscord#367]
**To Reproduce**
1. add new member on messenger 
2. the new member on messenger 1st chat triggers the error after adding him/her and the new member on messenger 1st chat wont display on discord
3. See error

> 
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.module.exports [as discord] (/usr/lib/node_modules/miscord/lib/createMessage/fromMessenger.discord.js:10:117)
    at Promise.all.channels.map (/usr/lib/node_modules/miscord/lib/messenger/listener.js:35:48)
    at Array.map (<anonymous>)
    at ApiEmitter.module.exports (/usr/lib/node_modules/miscord/lib/messenger/listener.js:34:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> 

**Specifications:**
 - OS:
Ubuntu 16.04.5 LTS 
 - Miscord Version:
 4.2.1
 - Node.js version:
v10.14.1

**Comment by Bjornskjald** [comment]
Fixed in https://github.com/miscord/miscord/commit/d2ec1259d8916bc6fe677cc4bb7d963421c5d61d
