### ISSUE TITLE
Files not being sent from discord to FB

### ISSUE THREAD

**Issue by baltitenger** [miscord/miscord#406]
```
Got Facebook error: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
Error: Got Facebook error: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
    at FacebookHttpApi.<anonymous> (/usr/lib/node_modules/miscord/node_modules/libfb/dist/BaseFacebookHttpApi.js:94:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/miscord/node_modules/tslib/tslib.js:104:62)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**To Reproduce**
It seems to happen every time when you send a file.

**Specifications:**
 - OS: Arch Linux

 - Version: 4.6.3

 - Node.js version: v11.6.0

**Proposed solution**
Files should not be re-uploaded on both platforms.
Just send an embed with the url of the attachment on the other platform.
That way you avoid the problem of different filesize limits and images won't be compressed again by the upload process.

**Comment by baltitenger** [comment]
Oh, you can't send a link to an image like that on messenger? I knew you can do that seamlessly with discord embeds so I assumed messenger supports it too.

**Comment by monckey100** [comment]
> It would be extremely uncomfortable for Messenger users to enter the link every time they try to see an image from Discord, but I agree on the files

Messenger supports og:title, og:description and og:image as meta data,
I am not sure about the API ends but with this you can attach the image by url and still get a preview... I do see there is a metadata option in the API.
