### ISSUE TITLE
AssertionError on login

### ISSUE THREAD

**Issue by erazemk** [miscord/miscord#464]
**Describe the bug**
Miscord successfully logs into FB and Discord, but shows the error shown at the bottom and restarts showing the error again so it has to be terminated.

**To Reproduce**
1. Install the latest miscord version using npm (5.0.4)
2. Create config using the config creator website
3. Run miscord using the created config

**Expected behavior**
Miscord runs normally without errors.

**Specifications:**
 - OS: Raspberry Pi OS (based on Debian Buster)
 - Version: Miscord 5.0.4 (from npm)
 - Node.js version: 14.12.0
 - npm version: 6.14.8

**Additional context**
Log:
```
 SUCCESS  16:47:44  ›  Worker process 4236 started.
  START   16:47:44  ›  Compressing old logs...
 SUCCESS  16:47:44  ›  All old logs compressed, starting Miscord
  INFO    16:47:44 FileConfig ›  Loading config from /home/ekokot/.config/Miscord/config.json
  START   16:47:44  ›  Launching Miscord v5.0.4
  START   16:47:44 login ›  Logging in...
  INFO    16:47:44 login › logLevel 'info'
  INFO    16:47:44 updateNotifier ›  Checking for updates...
  START   16:47:45 discord › login ›  Logging in to Discord...
 SUCCESS  16:47:45 discord › login ›  Logged in to Discord
  START   16:47:45 messenger › login ›  Logging in to Facebook...
 SUCCESS  16:47:47 messenger › login ›  Logged in to Facebook
 SUCCESS  16:47:47 login ›  Logged in
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
    at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
    at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
    at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
    at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
    at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
    at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
    at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
    at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
    at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
    at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17)
  ERROR   16:47:48 errorHandler ›  AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
  ERROR   16:47:48 errorHandler ›      at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
  ERROR   16:47:48 errorHandler ›      at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
  ERROR   16:47:48 errorHandler ›      at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
  ERROR   16:47:48 errorHandler ›      at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
  ERROR   16:47:48 errorHandler ›      at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
  ERROR   16:47:48 errorHandler ›      at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
  ERROR   16:47:48 errorHandler ›      at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
  ERROR   16:47:48 errorHandler ›      at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
  ERROR   16:47:48 errorHandler ›      at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
  ERROR   16:47:48 errorHandler ›      at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17) {
  ERROR   16:47:48 errorHandler ›    generatedMessage: false,
  ERROR   16:47:48 errorHandler ›    code: 'ERR_ASSERTION',
  ERROR   16:47:48 errorHandler ›    actual: false,
  ERROR   16:47:48 errorHandler ›    expected: true,
  ERROR   16:47:48 errorHandler ›    operator: '=='
  ERROR   16:47:48 errorHandler ›  }
  INFO    16:47:48 discord › listener ›  Got a Discord message
  INFO    16:47:48 discord › listener ›  Got a Discord message
  INFO    16:47:48  ›  Worker process 4236 died (2, null).
 SUCCESS  16:47:51  ›  Worker process 4247 started.
  START   16:47:51  ›  Compressing old logs...
 SUCCESS  16:47:51  ›  All old logs compressed, starting Miscord
  INFO    16:47:51 FileConfig ›  Loading config from /home/ekokot/.config/Miscord/config.json
  START   16:47:51  ›  Launching Miscord v5.0.4
  START   16:47:51 login ›  Logging in...
  INFO    16:47:51 login › logLevel 'info'
  INFO    16:47:51 updateNotifier ›  Checking for updates...
  START   16:47:52 discord › login ›  Logging in to Discord...
 SUCCESS  16:47:53 discord › login ›  Logged in to Discord
  START   16:47:53 messenger › login ›  Logging in to Facebook...
 SUCCESS  16:47:54 messenger › login ›  Logged in to Facebook
 SUCCESS  16:47:54 login ›  Logged in
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
    at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
    at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
    at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
    at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
    at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
    at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
    at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
    at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
    at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
    at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17)
  ERROR   16:47:55 errorHandler ›  AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
  ERROR   16:47:55 errorHandler ›      at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
  ERROR   16:47:55 errorHandler ›      at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
  ERROR   16:47:55 errorHandler ›      at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
  ERROR   16:47:55 errorHandler ›      at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
  ERROR   16:47:55 errorHandler ›      at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
  ERROR   16:47:55 errorHandler ›      at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
  ERROR   16:47:55 errorHandler ›      at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
  ERROR   16:47:55 errorHandler ›      at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
  ERROR   16:47:55 errorHandler ›      at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
  ERROR   16:47:55 errorHandler ›      at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17) {
  ERROR   16:47:55 errorHandler ›    generatedMessage: false,
  ERROR   16:47:55 errorHandler ›    code: 'ERR_ASSERTION',
  ERROR   16:47:55 errorHandler ›    actual: false,
  ERROR   16:47:55 errorHandler ›    expected: true,
  ERROR   16:47:55 errorHandler ›    operator: '=='
  ERROR   16:47:55 errorHandler ›  }
  INFO    16:47:55 discord › listener ›  Got a Discord message
  INFO    16:47:55 discord › listener ›  Got a Discord message
  INFO    16:47:56  ›  Worker process 4247 died (2, null).
 SUCCESS  16:47:58  ›  Worker process 4258 started.
  START   16:47:58  ›  Compressing old logs...
 SUCCESS  16:47:58  ›  All old logs compressed, starting Miscord
  INFO    16:47:58 FileConfig ›  Loading config from /home/ekokot/.config/Miscord/config.json
  START   16:47:58  ›  Launching Miscord v5.0.4
  START   16:47:58 login ›  Logging in...
  INFO    16:47:58 login › logLevel 'info'
  INFO    16:47:58 updateNotifier ›  Checking for updates...
  START   16:47:59 discord › login ›  Logging in to Discord...
 SUCCESS  16:48:00 discord › login ›  Logged in to Discord
  START   16:48:00 messenger › login ›  Logging in to Facebook...
 SUCCESS  16:48:02 messenger › login ›  Logged in to Facebook
 SUCCESS  16:48:02 login ›  Logged in
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
    at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
    at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
    at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
    at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
    at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
    at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
    at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
    at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
    at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
    at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17)
  ERROR   16:48:02 errorHandler ›  AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'
  ERROR   16:48:02 errorHandler ›      at Router._insert (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:286:9)
  ERROR   16:48:02 errorHandler ›      at Router._on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:188:8)
  ERROR   16:48:02 errorHandler ›      at Router.on (/usr/lib/node_modules/miscord/node_modules/find-my-way/index.js:73:8)
  ERROR   16:48:02 errorHandler ›      at Object.afterRouteAdded (/usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:232:16)
  ERROR   16:48:02 errorHandler ›      at /usr/lib/node_modules/miscord/node_modules/fastify/lib/route.js:163:31
  ERROR   16:48:02 errorHandler ›      at Object._encapsulateThreeParam (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:468:7)
  ERROR   16:48:02 errorHandler ›      at Boot.timeoutCall (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:379:5)
  ERROR   16:48:02 errorHandler ›      at Boot.callWithCbOrNextTick (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:360:19)
  ERROR   16:48:02 errorHandler ›      at Boot._after (/usr/lib/node_modules/miscord/node_modules/avvio/boot.js:235:26)
  ERROR   16:48:02 errorHandler ›      at Plugin.exec (/usr/lib/node_modules/miscord/node_modules/avvio/plugin.js:89:17) {
  ERROR   16:48:02 errorHandler ›    generatedMessage: false,
  ERROR   16:48:02 errorHandler ›    code: 'ERR_ASSERTION',
  ERROR   16:48:02 errorHandler ›    actual: false,
  ERROR   16:48:02 errorHandler ›    expected: true,
  ERROR   16:48:02 errorHandler ›    operator: '=='
  ERROR   16:48:02 errorHandler ›  }
  INFO    16:48:03 discord › listener ›  Got a Discord message
--- terminated ---
```

Config file:
```
{
  "messenger": {
    "username": "<email>",
    "password": "<pass>",
    "format": "*{username}*: {content}"
  },
  "discord": {
    "token": "<token>",
    "renameChannels": false
  },
  "channels": {
    "command": "<id>",
    "error": "<id>"
  },
  "api": {
  "username": "<user>",
  "password": "<pass>",
  "port": 9448
  },
  "checkUpdates": true,
  "timezone": "Europe/Ljubljana"
}
```

**Comment by ptrcnull** [comment]
Same as #462.
