### ISSUE TITLE
ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: useConnections

### ISSUE THREAD

**Issue by glensc** [miscord/miscord#470]
latest dev (e03bc8d77cac6256d20b82ba0d339013f0b7021a) is unable to stay up, crashes and reconnects:

```
  START   12:32:39  ›  Launching Miscord v5.0.4
  START   12:32:39 login ›  Logging in...
  INFO    12:32:39 login › logLevel 'info'
  START   12:32:39 discord › login ›  Logging in to Discord...
 SUCCESS  12:32:40 discord › login ›  Logged in to Discord
  START   12:32:40 messenger › login ›  Logging in to Facebook...
 SUCCESS  12:32:42 messenger › login ›  Logged in to Facebook
 SUCCESS  12:32:42 login ›  Logged in
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: useConnections
    at Timeout._onTimeout (/home/users/glen/scm/miscord/miscord/node_modules/avvio/plugin.js:81:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
  ERROR   12:32:52 errorHandler ›  Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: useConnections
  ERROR   12:32:52 errorHandler ›      at Timeout._onTimeout (/home/users/glen/scm/miscord/miscord/node_modules/avvio/plugin.js:81:19)
  ERROR   12:32:52 errorHandler ›      at listOnTimeout (internal/timers.js:549:17)
  ERROR   12:32:52 errorHandler ›      at processTimers (internal/timers.js:492:7) {
  ERROR   12:32:52 errorHandler ›    code: 'ERR_AVVIO_PLUGIN_TIMEOUT',
  ERROR   12:32:52 errorHandler ›    fn: [Function: useConnections]
  ERROR   12:32:52 errorHandler ›  }
  INFO    12:32:52  ›  Worker process 3052 died (2, null).
  INFO    12:32:53  › test { dataPath: '.' }
 SUCCESS  12:32:53  ›  Worker process 3079 started.
  START   12:32:53  ›  Compressing old logs...
 SUCCESS  12:32:53  ›  All old logs compressed, starting Miscord
  INFO    12:32:53 FileConfig ›  Loading config from /home/users/glen/scm/miscord/miscord-bot/config.json
  START   12:32:53  ›  Launching Miscord v5.0.4
  START   12:32:53 login ›  Logging in...
  INFO    12:32:53 login › logLevel 'info'
  START   12:32:53 discord › login ›  Logging in to Discord...
 SUCCESS  12:32:54 discord › login ›  Logged in to Discord
  START   12:32:54 messenger › login ›  Logging in to Facebook...
^C
```

unfortunately https://github.com/miscord/miscord/commit/e03bc8d77cac6256d20b82ba0d339013f0b7021a is just one huge massive commit, can't bisect it deeper, git commit leading to it, 8c20af3 aka git tag 5.0.4 works fine.

**Comment by ptrcnull** [comment]
Fixed in https://github.com/miscord/miscord/commit/a6abebc93632e464367127f7594da5617e7cc919, waiting for a merge to stable.
