### ISSUE TITLE
Getting a hard error on messages being sent from Facebook to Discord

### ISSUE THREAD

**Issue by bruce-armstrong** [miscord/miscord#486]
Just started happening about noon Pacific Time today.  Messages from Discord to Facebook Messanger work fine.  The error message in the miscord log is:

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
DiscordAPIError: 405: Method Not Allowed
    at C:\snapshot\miscord\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\snapshot\miscord\node_modules\snekfetch\src\index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  ERROR   19:56:58 errorHandler ›  DiscordAPIError: 405: Method Not Allowed
  ERROR   19:56:58 errorHandler ›      at C:\snapshot\miscord\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
  ERROR   19:56:58 errorHandler ›      at C:\snapshot\miscord\node_modules\snekfetch\src\index.js:215:21
  ERROR   19:56:58 errorHandler ›      at runMicrotasks (<anonymous>)
  ERROR   19:56:58 errorHandler ›      at processTicksAndRejections (internal/process/task_queues.js:93:5) {

**Comment by bruce-armstrong** [comment]
This may be related.  Looks like an issue that Discord is aware of and working on:

https://github.com/discordjs/discord.js/issues/5731

**Comment by bruce-armstrong** [comment]
Closing this out.  Discovered the problem was that my webhook for my channel was broken, and I was misled by the similarity to the error reported for discord.js above.
